services:
  ask-js:
    image: ask-js:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ask-js_web
#   uncommenting below may be useful depending on your setup
#    volumes:
#      - ./config.json:/askjs/config/config.json # configuration file
    restart: always
    ports:
      - '3579:3579'
  db:
    restart: unless-stopped
    image: postgres:17-alpine
    container_name: ask-js_db
    shm_size: 256MB
    environment:
      - POSTGRES_DB=askjs
      - POSTGRES_USER=askjs
      - POSTGRES_PASSWORD=askjs
    volumes:
      - ./db:/var/lib/postgresql/data