services:
    ask-js:
        image: ghcr.io/ihateblueb/ask-js:dev
        container_name: ask-js_web
        restart: always
        depends_on:
            - db
        ports:
            - '3579:3579'
        volumes:
            # run this command in the same place as this compose file to download the example configuration file, *must* be done before starting:
            #
            # wget -O config.json https://raw.githubusercontent.com/ihateblueb/ask-js/refs/heads/main/config/config.example.json
            #
            # this file *must* also be modified to replace "host" under "db" with "db", any other changes are of personal preference
            - ./config.json:/app/config/config.json

    db:
        restart: unless-stopped
        image: postgres:17-alpine
        container_name: ask-js_db
        shm_size: 256MB
        environment:
            - POSTGRES_DB=askjs
            - POSTGRES_USER=askjs
            - POSTGRES_PASSWORD=askjs
        volumes:
            - ./db:/var/lib/postgresql/data
